export type PlayerSession = {
    currentRoom: string;
    inventory: string[];
    pickedUpScroll: boolean;
    pickedUpButton: boolean;
    oasisPuzzleSolved: boolean;
    pickedUpTablet: boolean;
    pickedUpBook: boolean;
    openedBook: boolean;
    pickedUpDecryption: boolean;
    hydraulicsPuzzleSolved: boolean;
    LogbookPuzzleSolved: boolean;
    examinedTable: boolean;
    examinedDecryption: boolean;
    tablePickup: boolean;
    pickedUpManual: boolean;
    examinedHydraulics: boolean;
    pickedUpWatch: boolean;
    pickedUpPlant: boolean;
    pickedUpCup: boolean;
    pickedUpFilledCup: boolean;
    pickedUpLighter: boolean;
    deletedBrowser: boolean;
    deletedPictures: boolean;
    deletedScript: boolean;
    callNumber: number;
    drygroundValue: number;
    hydrogliphPuzzleValue: number;
    torchesLit: any[];
    crackedTileCount: number;
    aztecTalkValue: number;
    pickedUpPickaxe: boolean;
    rockBroken:boolean;
    pickedUpBrotherHeart:boolean;
    junglePuzzleSolved:boolean;
    pickedUpSmallPaper: boolean;
};
